name: Auto Commit Daily

on:
  schedule:
    - cron: "0 12 * * *"  # Executa diariamente às 12h UTC

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Git
        run: |
          git config --global user.name "andreluis2005"
          git config --global user.email "andreluis2005@gmail.com"

      - name: Criar/modificar arquivo
        run: echo "Atualização automática em $(date)" >> auto_update.log

      - name: Commit e Push
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git remote set-url origin https://$GH_PAT@github.com/andreluis2005/auto-commit-bot.git
          git add auto_update.log
          git commit -m "Commit automático - $(date)" || echo "Nenhuma alteração para commit"
          git push origin main
